cat > netlify.toml << EOF
[build]
  command = "npm run build"
  publish = "dist/ng-task-test/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "10"
EOF